### ISSUE TITLE
Bluetooth doesn't detect audio devices (ATH 9565)

### ISSUE THREAD

**Issue by kvn95ss** [chunnann/ATH9KFixup#11]
Wifi works (with 1.2MBps speed limit but meh I can live with that). Bluetooth sort of works, it can detect and pair with my android phone, but I can't get it to detect my KZ bluetooth cable or my wireless speakers. Any tips? 

Debug files if you need them - https://drive.google.com/open?id=1M1w0_1FktQVxNDXPyyuc05o7PC3rPibP

**Comment by htpcrig** [comment]
i dont think bluetooth has something to do with ATH9KFixup.

**Comment by kvn95ss** [comment]
Oh, I guess so. Now it works though, I didn't do anything to fix it.
Closing the thread.
